# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build the docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_IMAGE_TAG: ${{github.sha}}

permissions:
  id-token: write
  contents: read



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Configure AWS Credentials region audience
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::767397826387:role/online_shop_ci_cd_pipeline

    # - uses: actions/checkout@v3
    # - name: Build Docker image
    #   run: docker build -t my-first-docker-image:${{ github.run_number }} .

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    
    - name: Terraform Init
      working-directory : ./infra
      run: terraform init

    - name: Terraform Apply
      working-directory : ./infra
      run: terraform apply -auto-approve -var docker_image_tag=$DOCKER_IMAGE_TAG

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397826387.dkr.ecr.us-east-1.amazonaws.com
          
    # - uses: actions/checkout@v3 
    # - name: Get commit hash
    #   id: get-commit-hash
    #   run: echo "::set-output name=commit-hash::$(git rev-parse HEAD)"
     
    - name: Build Docker image
      run: docker build -t terraform_ecr_repo:$DOCKER_IMAGE_TAG  .
      
    - name: Tag the Docker image
      run: docker tag terraform_ecr_repo:$DOCKER_IMAGE_TAG  767397826387.dkr.ecr.us-east-1.amazonaws.com/terraform_ecr_repo:$DOCKER_IMAGE_TAG
      
    - name: Push the image to Amazon ECR
      run: docker push 767397826387.dkr.ecr.us-east-1.amazonaws.com/terraform_ecr_repo:$DOCKER_IMAGE_TAG

    