name: Release

on:
  push:
    tags: "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - run: npm ci
        working-directory: ui
      - run: npm run build
        working-directory: ui
      - run: cp -r ./ui/build/. ./src/main/resources/static/.
      - run: mvn -q "-DfinalName=online-shop-v0.0.1" clean package
      - uses: "ncipollo/release-action@v1"
        with:
          # $GITHUB_REF_NAME
          artifacts: "target/online-shop-v0.0.1.jar"
          allowUpdates: true
          name: v0.0.1
